FROM node:20-slim as builder

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_FRONTEND_URL
ARG FRONTEND_PORT

ADD package*.json app/
WORKDIR /app
RUN npm install

ADD next.config.mjs ./ 
ADD postcss.config.mjs ./ 
ADD tailwind.config.ts ./
ADD tsconfig.* ./
ADD src ./src
RUN npm run build

from node:20-alpine
copy --from=builder /app/.next/standalone /

ARG FRONTEND_PORT
ENV PORT=${FRONTEND_PORT}
ENV HOSTNAME=0.0.0.0
ENTRYPOINT [ "node", "server.js" ]