FROM node:20-slim as builder

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_FRONTEND_URL

ADD package*.json app/
WORKDIR /app
RUN npm install

ADD next.config.mjs ./ 
ADD postcss.config.mjs ./ 
ADD tailwind.config.ts ./
ADD tsconfig.* ./
ADD src ./src
RUN npm run build

FROM node:20-alpine
COPY --from=builder /app/.next/standalone /app
COPY --from=builder /app/.next/static /app/.next/static
WORKDIR /app

ENV PORT=
ENV HOSTNAME=
ENTRYPOINT [ "node", "server.js" ]