FROM node:20-slim as builder

ARG NEXT_PUBLIC_URL
ARG FRONTEND_CONTAINER_PORT

ADD package*.json app/
WORKDIR /app
RUN npm install

ADD next.config.mjs ./ 
ADD postcss.config.mjs ./ 
ADD tailwind.config.ts ./
ADD tsconfig.* ./
ADD src ./src
RUN npm run build
RUN cp -r .next/static .next/standalone/.next/static

FROM node:20-alpine

COPY --from=builder /app/.next/standalone /
COPY --from=builder /app/.next/static /.next/static

ARG FRONTEND_CONTAINER_PORT
ENV PORT=${FRONTEND_CONTAINER_PORT}
ENV HOSTNAME=0.0.0.0

ENTRYPOINT [ "node", "server.js" ]