FROM node:20-alpine as builder

ADD package*.json app/
WORKDIR /app
RUN npm install

ADD tsconfig*.json ./
ADD src ./src
RUN npm run build

from node:20-alpine
copy --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

ENTRYPOINT [ "node", "dist/main.js" ]