name: NationalRecords

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

  frontend: 
    build:
      context: ../FrontEnd
      dockerfile: dockerfile
      args:
        NEXT_PUBLIC_URL: ${PUBLIC_URL} 
        FRONTEND_CONTAINER_PORT: ${FRONTEND_PORT}
    restart: always
    image: nr-frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      IS_DEV: true
      JWT_SECRET: ${JWT_SECRET}
      NEXT_PUBLIC_URL: ${PUBLIC_URL}
      BACKEND_INTERNAL_URL : ${API_URL}
      HOST: "0.0.0.0"
      PORT: ${FRONTEND_PORT}

  backend:
    build: ../graphql-api
    restart: always
    image: nr-backend
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      JWT_SECRET : ${JWT_SECRET}
      DB_ROOT_PASSWORD: ${DB_PASSWORD}
      PUBLIC_URL: ${PUBLIC_URL}
      FRONTEND_INTERNAL_URL: ${FRONTEND_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PORT: ${API_PORT}
      
    depends_on:
      - mysql


  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PUBLIC_PORT}:${DB_PORT}
    volumes:
      - ./data:/docker-entrypoint-initdb.d