name: NationalRecords

services:

  FrontEnd: 
    restart: always
    image: nr-frontend-dev
    ports:
      - 80:${FRONTEND_PORT}
    environment:
      NEXT_PUBLIC_API_URL: ${PUBLIC_API_URL}
      API_URL : ${API_URL}
      NEXT_PUBLIC_FRONTEND_URL: ${FRONTEND_PUBLIC_URL}
      HOST: ${HOST}
      PORT: ${FRONTEND_PORT}

  BackEnd:
    restart: always
    image: nr-backend-dev
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      PUBLIC_FRONTEND_URL: ${FRONTEND_PUBLIC_URL}
      FRONT_URL:  ${FRONTEND_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_ROOT_PASSWORD: ${DB_PASSWORD}
      PORT: ${API_PORT}
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PUBLIC_PORT}:${DB_PORT}
    volumes:
      - ./data:/docker-entrypoint-initdb.d

